---
title: 'Project : Broken devices S7'
author: "Solène PETITO"
output:
  html_document: default
  pdf_document: default
  word_document: default
date: "2024-07-01"
editor_options: 
  markdown: 
    wrap: 72
---

# **SEMAINE DU 15 JUILLET 2024 au 20 JUILLET 2024 :**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
############### MODULE 1 : Chargement des librairies

library(openxlsx)
library(readxl)
library(ggplot2)
library(stringr)
library(tibble)
library(dplyr)
library(plotly) # permet de faire des graphes intéractifs
library(corrplot) # permet de réqliser des matrices de corrélation
library(tidyr)
library(RColorBrewer) # librairie pour les palettes de couleurs
library(viridis) # palette de couleurs > 25 nuances
library(Polychrome)
library(gridExtra) # afficher les graphes côte à côte
library(grid)

```

```{r include=FALSE}
############### MODULE 2 : Création de fonctions

# fonction func1 qui prend en entrée un jeu de données (don) et le nom d'une colonne de type Cri (Caratère répétitive) de ce jeu de données (colonne), sous forme de chaine de caractères et sans préciser de numéro à la fin de celle-ci  : ex : "COHABITATION_DYSFONCTION_A" ou "GENE_PROBLEMES_A". Elle renvoit en sortie une matrice a 2 lignes et 25 colonnes, indiquant en ligne 1 le type de dysfonctionnement, et en ligne 2 une modalité moyenne calculée pour la variable donnée en entrée pour chaque type de dysfonctionnements.

func1 <- function (don,colonne){
  matrice <- matrix(0,nrow=2,ncol=25)
  matrice[1,] <- c(1:25)
  df = don[which(don$RIDENTIFICATION_PROBLEMES!="27"),]
  variable=df$RIDENTIFICATION_PROBLEMES
  for (pb in 1:25){
    vec=c()
    for (i in 1:length(variable)){
      ligne=str_extract_all(variable[i], ".{2}")[[1]]
      ligne=sub("^0+", "", ligne)
      if (pb %in% ligne){
        num=as.character(pb)
        nom_colonne=paste0(colonne,num)
        valeur=df[i,nom_colonne]
        if(!is.null(valeur) && !is.na(valeur)){
          vec=c(vec,valeur)
        }
      }
    }
    if (length(vec) > 0) {
    matrice[2, pb] <- round(mean(vec))
  } else {
    matrice[2, pb] <- 0
  }
  }
  return(matrice)
}
##########################################

# Création d'une fonction **Count_VCM** (VCM = Variable à choix multiples) permettant d'afficher pour les variables à choix multiples UNIQUEMENT, le nombre de fois où chaque modalité est renseignée dans toute la colonne. Elle prend en entrée une variable à choix multiple (*variable*), issue de la base de données, et son nombre total de modalités (*nb_de_modalites*), et renvoit une matrice indiquant en ligne 1 le numéro de la modalité, et en ligne 2 le nombre de fois où les répondants l'on choisit.

Count_VCM <- function(variable,nb_de_modalites){
  mat <- matrix(0,nrow=2,ncol=nb_de_modalites)
  mat[1,]=c(1:nb_de_modalites)
  for (i in 1:length(variable)){
    ligne=str_extract_all(variable[i],".{2}")[[1]]
    vec=sub("^0+","",ligne)
    for (j in 1:length(vec)){
      for (k in 1:ncol(mat)){
        if (vec[j]==mat[1,k]){
          mat[2,k]=mat[2,k]+ 1 # mettre "+1" à la place de "data[i,"poids"]" si on ne concidère pas les poids
        }
      }
    }
  }
  return(mat)
}

##########################################

# Pour éviter d'avoir à afficher les numéros des modalités sur chaques graphes, je stocke directement les libellés des modalités dans des vecteurs

label_RIDENTIFICATION_PROBLEME = c("Problème avec l’écran","Problème de sensibilité du tactile","Problème avec l’appareil photo","Problème avec la lampe torche ou le flash","Problème avec le GPS","Problème avec le micro","Problème de son","Problème de prise jack","Problème de chargement","Problème de batterie","Problème de Wi-Fi","Problème de capteurs","Problème de Bluetooth ou de transferts de fichiers sans fil","Problème de téléphonie","Problème d’accès à Internet","Problème avec les boutons","Problème de vibreur","Stockage saturé","Système d’exploitation non mis à jour","Applications ne pouvant pas être téléchargées ou mises à jour","Problème lié à une fonctionnalité manquante","Fonctionnalité qui ne marche plus","Dysfonctionnement logiciel","Problèmes avec des applications","Problème de lenteur","Autre")

label_ACQUISITION = c("Quelqu’un me l’a offert ou donné","Quelqu’un me l’a prêté","Je l’ai acheté","Je l’ai obtenu dans le cadre de mon contrat avec mon opérateur","Mon employeur me l’a fourni","Je l’ai loué","Je ne me souviens pas","Obtenu par un autre moyen")

label_COHABITATION = c("Dès que j’ai décelé le dysfonctionnement","Moins d’un mois","Entre 1 et 6 mois","Entre 6 mois et 2 ans","Plus de deux ans","Je ne sais pas" )

label_GENE=c("Très gênant","Plutôt gênant","Plutôt pas gênant","Pas gênant du tout")

label_INT_REPARATION= c("Oui, par moi-même","Oui, par le SAV ou un réparateur","Oui, par une connaissance","Pas pour l’instant", "Non")

label_RECENCE <- c("Dès la première utilisation","En moins de 3 mois","Entre 3 mois et 1 an","Entre 1 et 2 ans","Entre 2 et 3 ans","Plus de 3 ans","Je ne sais pas")

label_REPARATION <- c("Oui et le problème est resolu","Oui mais le problème na pas pu être résolu","Non, le problème s’est résolu tout seul au bout d’un moment","Non, peut être plus tard","Non, je ne pense pas tenter de résoudre le problème")

label_OS <- c("IOS (Apple)","Android","Autre","Je ne sais pas")

label_ETAT= c("Neuf","D'occasion","Reconditionné","Je ne sais pas" )

label_COHAB_2 <- c("Moins d'un mois","Entre 1 et 6 mois","Entre 6 mois et 2 ans","Plus de 2 ans")

label_RAISON_UTIL_PB <- c("Cela serait trop coûteux de résoudre le(s) problème(s) ou de remplacer mon smartphone",
"J’attends une opportunité", "Je ne peux pas résoudre le problème car le smartphone ne m’appartient pas","Je ne sais pas comment résoudre le(s) problème(s)","Je veux faire durer mon téléphone le plus longtemps possible","Ce(s) problème(s) ne m’impacte(nt) pas tant que ça au quotidien","Je n’ai pas pris le temps de m’en occuper, de chercher une solution","Mon téléphone est trop récent pour que je le fasse réparer ou que je le remplace","La résolution du (ou des) problème(s) est trop difficile ou incertaine","Ça me donne un prétexte pour moins l’utiliser","Cela ne vaut pas la peine de résoudre le(s) problème(s)","Mon smartphone a une particularité difficile à retrouver si je devais le remplacer","Autre")

label_IMPACT <- c("Usage global du smartphone","Communication ","Réseaux sociaux ","Cartes et guidage GPS","Jeux","Navigation web","Streaming musique et vidéo","Outils de productivité ","Logiciels et applications professionnelles dédiées","Photo, vidéo et autres activités de création","Identification bancaire, paiement sans contact","Tickets dématérialisés ","Courses et achats en ligne","Autre","Aucun")

label_dys <- c("Stockage","Matériel","Mise à jour","Dys divers")
```

```{r include=FALSE}
# Catégorisation des dysfonctionnements

label_dys <- c("Stockage","Matériel","Mise à jour","Dys divers")

materiel <- c(1,2,1,3,4,6,7,8,9,10,12,16,17)
dys_divers <- c(5,11,13,14,15,21,22,23,24,25)
stockage <- c(18)
maj <- c(19,20)

# Trouver la liste qui contient le plus d'éléments pour après définir le nombre de colonnes de notre matrice
max_length <- max(length(materiel), length(dys_divers), length(stockage), length(maj))

# Initialiser la matrice avec des zéros
matrice_cat <- matrix(0, nrow = 4, ncol = max_length)

# Remplir les lignes de la matrice avec les listes
matrice_cat[1, 1:length(stockage)] <- stockage
matrice_cat[2, 1:length(materiel)] <- materiel
matrice_cat[3, 1:length(maj)] <- maj
matrice_cat[4, 1:length(dys_divers)] <- dys_divers

# Afficher la matrice
print(matrice_cat)
```


**OBJECTIF :** *Analyser la base de données *

## **ANALYSE DE LA BASE DE DONNÉES**

```{r include=FALSE}
# Import des données

data <- readRDS("/home/solene_petito/Bureau/Stage/Broken_devices/data/data1.rds") # base de données sur laquelle on va appliquer tous les changements

# Exporter la base de données en format Excel
write.xlsx(data, file = "/home/solene_petito/Bureau/Stage/Broken_devices/data/database.xlsx")

Broken_Devices_Data <- read.csv("/home/solene_petito/Bureau/Stage/Broken_devices/data/Broken-Devices-Data1-xlsx.csv",row.names=1) # base de données initiale sur laquelle on pourra se référer pour voir si les chgts ont bien été appliqués

# nombre d'observations
nb_obs <- nrow(data) # 968 

# nombre de variables 
nb_var <- ncol(data) # 164
```

```{r include=FALSE}
View(data)
View(Broken_Devices_Data)
```

```{r include=FALSE}
REPARATION <- c(1:5)
matrice_REP=matrix(0,nrow=2,ncol=length(REPARATION))
matrice_REP[1,]=REPARATION

colonne_deb <- which(names(data) == "REPARATION_A1")
#print(colonne_deb) # 81

colonne_fin <- which(names(data) == "REPARATION_A25")
#print(colonne_fin) # 105

df <- data[,colonne_deb:colonne_fin]

for (i in 1 :ncol(df)){
    for (j in 1:nrow(df)){
      val=df[j,i]
      if(!is.na(val)&& !is.null(val)){
        matrice_REP[2,val]=matrice_REP[2,val]+1
      }
    }
  }
```

### **I ) Variable ETAT ANCIEN TEL **

```{r}
variable=data[which(data$RETAT_ANCIEN_TEL!=""),"RETAT_ANCIEN_TEL"]
nb_de_modalites=10
matrice=Count_VCM(variable,nb_de_modalites)
matrice[2,]=round(matrice[2,])

matrice
```


```{r}
variable = data[which(data$RETAT_ANCIEN_TEL!=""),"RETAT_ANCIEN_TEL"]

mat = matrix(0,ncol=10,nrow=10)
for (i in 1:ncol(mat)){
  for (j in 1:length(variable)){
    liste_etats=str_extract_all(variable[j], ".{2}")[[1]]
    liste_etats=as.numeric(liste_etats)
    if (i %in% liste_etats){
      for (k in 1:length(liste_etats) ){
        etat=liste_etats[k]
        mat[etat,i]=mat[etat,i]+1
      }
    }
  }
}

mat

```

```{r}
sum(mat[2,-2])
```


```{r}
for (i in 1:ncol(mat)){
  mat[i,i]=mat[i,i]-sum(mat[i,-i])
}
mat
```


```{r}
# cor.mtest est une fonction qui calcule la matrice de corrélation d'un jeu de donnée à l'aide la fonction cor.test, et qui renvoit la matrice de corrélation en question :

cor.mtest <- function(mat, ...) {
        mat <- as.matrix(mat)
        n <- ncol(mat)
        p.mat<- matrix(NA, n, n)
        diag(p.mat) <- 0
        for (i in 1:(n - 1)) {
            for (j in (i + 1):n) {
                tmp <- cor.test(mat[, i], mat[, j], ...)
                p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
            }
        }
      colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
      p.mat
}
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
 p.mat <- cor.mtest(mat) # on stocke le résultat de notre fonction dans une variable p.mat
 
# On représente graphiquement la matrice obtenue, grâce à la foonction corrplot : 
 
corrplot(cor(mat), method="color", col=col(200),  
             type="upper", order="hclust", 
             addCoef.col = "black", # Ajout du coefficient de corrélation
             tl.col="black", tl.srt=45, #Rotation des etiquettes de textes
             # Combiner avec le niveau de significativité
             p.mat = p.mat, sig.level = 0.8, insig = "blank", 
             # Cacher les coefficients de corrélation sur la diagonale
             diag=FALSE)
```


```{r}
library(corrplot)

mcor=cor(mat)

custom_names <- c("Mon téléphone fonctionnait bien","Mon téléphone fonctionnait mais il lui manquait une ou plusieurs fonctionnalités" ,"Mon téléphone était complètement inutilisable","La durée de vie de la batterie était faible","Le stockage de mon téléphone était insuffisant","Mon téléphone était lent","Mon téléphone était physiquement endommagé","Mon téléphone avait des dysfonctionnements","Autre raison","Je ne me souviens pas")
#colnames(mcor) <- custom_names
#rownames(mcor) <- custom_names

corrplot(mcor, type="upper", order="hclust", tl.col="black", tl.srt=45,diag=FALSE)
```
### **2 ) Graphe du type de Résolution en fonction du degré de gêne**

```{r}
# Initialisation des vecteurs pour stocker les valeurs de recence, année, et mois
recence <- c()
annee <- c()
mois <- c()
gene <- c()
rep <- c()

# Filtrer les données pour exclure les problèmes identifiés avec le code "27"
df <- data[which(data$RIDENTIFICATION_PROBLEMES != "27"),]

# Parcourir les colonnes de 81 à 105 (indice des colonnes reparation)
for (i in 81:105) {
  # Parcourir les lignes du dataframe filtré
  for (j in 1:nrow(df)) {
    val <- df[j, i]
    # Vérifier si la valeur n'est pas NA avant de vérifier si elle est 4 ou 5
    if (!is.na(val) && (val == 4 || val == 5)) {
      RECENCE <- df[j, i - 25]
      # Vérifier si RECENCE n'est pas NA et val n'est pas NULL
      if (!is.na(RECENCE)) {
        recence <- c(recence, RECENCE)
        annee <- c(annee, df[j, "DATEOBTENTIONSMART_1"])
        mois <- c(mois, df[j, "DATEOBTENTIONSMART_2"])
        gene <- c(gene,df[j, i - 50])
        rep = c(rep,val)
      }
    }
  }
}

# Suppression de la raison 7 dans la liste recence 

indices_rec_7= which(recence==7)
gene=gene[-c(indices_rec_7)]
rep = rep[-c(indices_rec_7)]

# Afficher les résultats pour vérifier
print(head(recence))
print(head(annee))
print(head(mois))
print(head(gene))
print(head(rep))
```


```{r echo=FALSE}
gene_pbs_non_resolus=as.matrix(table(gene))
gene_pbs_non_resolus
```

```{r echo=FALSE}
gene_tente_pas_reussi <- c()
gene_pbs_resolus <- c()
gene_resolu_seul <- c()

# Filtrer les données pour exclure les problèmes identifiés avec le code "27"
df <- data[which(data$RIDENTIFICATION_PROBLEMES != "27"),]

# Parcourir les colonnes de 81 à 105 (indice des colonnes reparation)
for (i in 81:105) {
  # Parcourir les lignes du dataframe filtré
  for (j in 1:nrow(df)) {
    val <- df[j, i]
    # Vérifier si la valeur n'est pas NA avant de vérifier si elle est 4 ou 5
    if (!is.na(val) && (val == 1)) {
      g <- df[j, i - 50]
      # Vérifier si RECENCE n'est pas NA et val n'est pas NULL
      if (!is.na(g)) {
        gene_pbs_resolus <- c(gene_pbs_resolus,g)
      }
    }
    if (!is.na(val) && (val == 2)) {
      g <- df[j, i - 50]
      # Vérifier si RECENCE n'est pas NA et val n'est pas NULL
      if (!is.na(g)) {
        gene_tente_pas_reussi <- c(gene_tente_pas_reussi,g)
      }
    }
    if (!is.na(val) && (val == 3)) {
      g <- df[j, i - 50]
      # Vérifier si RECENCE n'est pas NA et val n'est pas NULL
      if (!is.na(g)) {
        gene_resolu_seul <- c(gene_resolu_seul,g)
      }
  }
  }
}

gene_pbs_resolus=as.matrix(table(gene_pbs_resolus))
gene_tente_pas_reussi=as.matrix(table(gene_tente_pas_reussi))
gene_resolu_seul = as.matrix(table(gene_resolu_seul))

print(gene_pbs_resolus)
print(gene_tente_pas_reussi)
print(gene_resolu_seul)
```


```{r include=FALSE}
# Types de résolution en abscisse et gêne en ordonné
indices_rep_4= which(rep==4)
gene_pbs_non_resolus_rep_4 <- gene[-c(indices_rep_4)] 
gene_pbs_non_resolus_rep_4 <- as.matrix(table(gene_pbs_non_resolus_rep_4))

indices_rep_5= which(rep==5)
gene_pbs_non_resolus_rep_5 <- gene[-c(indices_rep_5)] 
gene_pbs_non_resolus_rep_5 <- as.matrix(table(gene_pbs_non_resolus_rep_5))




mat=matrix(0,nrow=3,ncol=5)
mat[,1]=gene_pbs_resolus[,1]
mat[,2]=gene_tente_pas_reussi[,1]
mat[,3] = gene_resolu_seul[,1]
mat[,4]=gene_pbs_non_resolus_rep_4 
mat[,5] =gene_pbs_non_resolus_rep_5

print(mat)
print(sum(mat))

total=rowSums(mat)
print(total)

normalize <- function(x) {
  return(round(x*100/total))
}

# Transposer le résultat pour obtenir la même structure que la matrice originale
normalized_mat <- t(apply(mat, 2, normalize))
print(normalized_mat)
```

```{r}
mat
```

```{r}
resolution_label=c("Le problème est resolu","Le problème n'a pas pu être résolu","Le problème s’est résolu tout seul au bout d’un moment","Le problème sera peut-être résolu plus tard","Je ne pense pas tenter de résoudre le problème")

Catégorie = factor(label_GENE[1:3], levels = label_GENE[1:3])

df_T1 <- data.frame(Catégorie = Catégorie, valeurs = mat[,1], Légende = factor("Le problème est resolu",levels=resolution_label))
df_T2 <- data.frame(Catégorie = Catégorie, valeurs = mat[,2], Légende = factor("Le problème n'a pas pu être résolu",levels=resolution_label))
df_T3 <- data.frame(Catégorie = Catégorie, valeurs = mat[,3], Légende = factor("Le problème s’est résolu tout seul au bout d’un moment",levels=resolution_label))
df_T4 <- data.frame(Catégorie = Catégorie, valeurs = mat[,4], Légende = factor("Le problème sera peut-être résolu plus tard",levels=resolution_label))
df_T5 <- data.frame(Catégorie = Catégorie, valeurs = mat[,5], Légende = factor("Je ne pense pas tenter de résoudre le problème",levels=resolution_label))

# Combiner les deux data frames
df_combined <- rbind(df_T1, df_T2,df_T3,df_T4,df_T5)

# Créer un diagramme en barres empilées
p5 <- ggplot(df_combined, aes(x = Catégorie, y = valeurs, fill = Légende)) +
  geom_bar(stat = "identity", position = "stack") + # mettre position = "dodge" si on veut des barres côtes à côtes
  labs(title = "Résolution en fonction du degrés de gêne",
       x = "Degrés de gêne",
       y = "Nombre de dysfonctionnements") +
  scale_fill_manual(values = c("Le problème est resolu"="#33a02c",
"Le problème n'a pas pu être résolu"="#FFD700","Le problème s’est résolu tout seul au bout d’un moment"="gray","Le problème sera peut-être résolu plus tard"="#fdb462","Je ne pense pas tenter de résoudre le problème"="#e31a1c")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.title.x = element_text( face = "bold"), 
        axis.title.y = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) 

p5_interactif <- ggplotly(p5)

# Afficher le graphique interactif
p5_interactif 
```

```{r include=FALSE}
resolution_label=c("Oui et le problème est resolu",
"Oui mais le problème na pas pu être résolu","Non, le problème s’est résolu tout seul au bout d’un moment","Non, peut être plus tard","Non, je ne pense pas tenter de résoudre le problème")

Catégorie = factor(label_GENE, levels = label_GENE)

df_T1 <- data.frame(Catégorie = Catégorie, valeurs = normalized_mat[,1], Légende = factor("Oui et le problème est resolu",levels=resolution_label))
df_T2 <- data.frame(Catégorie = Catégorie, valeurs = normalized_mat[,2], Légende = factor("Oui mais le problème na pas pu être résolu",levels=resolution_label))
df_T3 <- data.frame(Catégorie = Catégorie, valeurs = normalized_mat[,3], Légende = factor("Non, le problème s’est résolu tout seul au bout d’un moment",levels=resolution_label))
df_T4 <- data.frame(Catégorie = Catégorie, valeurs = normalized_mat[,4], Légende = factor("Non, peut être plus tard",levels=resolution_label))
df_T5 <- data.frame(Catégorie = Catégorie, valeurs = normalized_mat[,5], Légende = factor("Non, je ne pense pas tenter de résoudre le problème",levels=resolution_label))

# Combiner les deux data frames
df_combined <- rbind(df_T1, df_T2,df_T3,df_T4,df_T5)

# Créer un diagramme en barres empilées
p6 <- ggplot(df_combined, aes(x = Catégorie, y = valeurs, fill = Légende)) +
  geom_bar(stat = "identity", position = "stack") + # mettre position = "dodge" so on veut des barres côtes à côtes
  labs(title = "Résolution en fonction du degrés de gêne",
       x = "Degrés de gêne",
       y = "Pourcentage de dysfonctionnements") +
  scale_fill_manual(values = c("Oui et le problème est resolu"="#33a02c",
"Oui mais le problème na pas pu être résolu"="#FFD700","Non, le problème s’est résolu tout seul au bout d’un moment"="gray","Non, peut être plus tard"="#fdb462","Non, je ne pense pas tenter de résoudre le problème"="#e31a1c")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.title.x = element_text( face = "bold"),  
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        axis.title.y = element_text(face = "bold"),legend.position="none") 

p6_interactif <- ggplotly(p6)

# Afficher le graphique interactif
p6_interactif 
```

```{r echo=FALSE}
# Utiliser subplot pour afficher les graphiques côte à côte
library(plotly)

subplot(
  p5_interactif, p6_interactif,
  nrows = 1, 
  titleX = TRUE, 
  titleY = TRUE,
  shareY = FALSE,
  widths = c(0.45, 0.45)  # Ajuster les largeurs pour plus d'espace
) %>%
  layout(
    title = list(
      text = "Résolution en fonction du degrés de gêne",
      font = list(size = 20, color = "black", family = "Arial", face = "bold")  # Taille augmentée pour le titre principal
    ),
    annotations = list(
      list(
        x = 0.2, y = 1.05, text = "Sur 787 dysfonctionnements", 
        showarrow = FALSE, xref = "paper", yref = "paper", xanchor = 'center', yanchor = 'bottom', font = list(size = 14, color = "black", family = "Arial", face = "bold")  # Correction pour la police en gras
      ),
      list(
        x = 0.8, y = 1.05, text = "Sur le même niveau", 
        showarrow = FALSE, xref = "paper", yref = "paper", xanchor = 'center', yanchor = 'bottom', font = list(size = 14, color = "black", family = "Arial", face = "bold")  # Correction pour la police en gras
      )
    ),
    margin = list(t = 100),  # Ajuster les marges pour plus d'espace pour les titres
    xaxis = list(domain = c(0, 0.45)),  # Ajuster la position du premier graphique
    xaxis2 = list(domain = c(0.55, 1))  # Ajuster la position du deuxième graphique
  )


```





```{r echo=FALSE }
indice_colonne <- which(names(data) == "GENE_PROBLEMES_A1")
print(indice_colonne) # 106

indice_colonne <- which(names(data) == "REPARATION_A1")
print(indice_colonne) # 81

indice_colonne <- which(names(data) == "GENE_PROBLEMES_A25")
print(indice_colonne) # 80

indice_colonne <- which(names(data) == "REPARATION_A25")
print(indice_colonne) #105

81-31

```
